import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { findContainerNames, tokenize } from '../src/template/lexer.ts';
import { parseTemplate } from '../src/template/parser.ts';
import { passThroughContext, renderNodes, renderTemplate, type RenderContext } from '../src/template/renderer.ts';
import { InvalidFileError } from '../src/util/errors.ts';
import type { TemplateNode } from '../src/template/ast.ts';

describe('tokenize', () => {
  test('separates directives from text', () => {
    expect(tokenize('a<!--NAME-->b')).toEqual([
      { kind: 'text', text: 'a' },
      { kind: 'directive', name: 'NAME', closing: false, raw: '<!--NAME-->', line: 1 },
      { kind: 'text', text: 'b' },
    ]);
  });

  test('recognises closing directives', () => {
    const [open, , close] = tokenize('<!--IFNAME-->x<!--/IFNAME-->');
    expect(open).toMatchObject({ name: 'IFNAME', closing: false });
    expect(close).toMatchObject({ name: 'IFNAME', closing: true, raw: '<!--/IFNAME-->' });
  });

  // Templates open with a multi-line banner comment that must reach the output
  // untouched, so only bare uppercase names count as directives.
  test.each([
    '<!-- NAME -->',
    '<!--name-->',
    '<!--Not A Tag-->',
    '<!--\n\nGenerated by Ork HERO Templates\n\n-->',
    '<!--NAME.WITH.DOTS-->',
  ])('treats %p as text, not a directive', (comment) => {
    expect(tokenize(comment)).toEqual([{ kind: 'text', text: comment }]);
  });

  test('tracks line numbers across text and directives', () => {
    const tokens = tokenize('one\ntwo\n<!--A-->\n<!--B-->');
    expect(tokens.filter((t) => t.kind === 'directive')).toMatchObject([
      { name: 'A', line: 3 },
      { name: 'B', line: 4 },
    ]);
  });

  test('leaves an unterminated comment as text', () => {
    expect(tokenize('a<!--NAME')).toEqual([{ kind: 'text', text: 'a<!--NAME' }]);
  });

  test('collects the names that are ever closed', () => {
    const names = findContainerNames(tokenize('<!--A--><!--B-->x<!--/B-->'));
    expect([...names]).toEqual(['B']);
  });
});

describe('parseTemplate', () => {
  test('nests containers and leaves unclosed names as tags', () => {
    const { body } = parseTemplate('<!--POWERS--><!--POWER_COST--><!--/POWERS-->');
    expect(body).toHaveLength(1);
    const container = body[0]!;
    expect(container.kind).toBe('container');
    if (container.kind === 'container') {
      expect(container.name).toBe('POWERS');
      expect(container.children).toMatchObject([{ kind: 'tag', name: 'POWER_COST' }]);
    }
  });

  test('extracts metadata and removes it from the body', () => {
    const parsed = parseTemplate(
      '<!--TEMPLATE_NAME-->Ork<!--/TEMPLATE_NAME-->' +
        '<!--TEMPLATE_DESCRIPTION-->Nice<br>sheet<!--/TEMPLATE_DESCRIPTION-->' +
        '<!--FILE_EXTENSION-->html<!--/FILE_EXTENSION-->rest',
    );
    expect(parsed.name).toBe('Ork');
    expect(parsed.description).toBe('Nice<br>sheet');
    expect(parsed.fileExtensions).toEqual(['html']);
    expect(parsed.body).toEqual([{ kind: 'text', text: 'rest' }]);
  });

  test('collects regex and literal replacements', () => {
    const parsed = parseTemplate(
      '<!--REG_REPLACE--><!--REGSTRING-->\\b1/2\\b<!--/REGSTRING--><!--REPSTRING-->½<!--/REPSTRING--><!--/REG_REPLACE-->' +
        '<!--REPLACE--><!--DEFSTRING-->abc<!--/DEFSTRING--><!--REPSTRING-->xyz<!--/REPSTRING--><!--/REPLACE-->',
    );
    expect(parsed.replacements).toMatchObject([
      { kind: 'regex', pattern: '\\b1/2\\b', replacement: '½' },
      { kind: 'literal', find: 'abc', replacement: 'xyz' },
    ]);
    expect(parsed.body).toEqual([]);
  });

  test('reports a replacement block that is missing a part', () => {
    expect(() =>
      parseTemplate('<!--REG_REPLACE--><!--REPSTRING-->x<!--/REPSTRING--><!--/REG_REPLACE-->'),
    ).toThrow(/missing its <!--REGSTRING--> part/);
  });

  test('reports mismatched containers with both line numbers', () => {
    expect(() => parseTemplate('<!--A-->\n\n<!--B-->\n<!--/A-->\n<!--/B-->')).toThrow(
      /Found <!--\/A-->, but the container still open is <!--B--> from line 3/,
    );
  });

  // A name that is never closed anywhere is simply a tag, so the unclosed
  // error only fires when a name is opened more often than it is closed.
  test('treats a name with no closing tag anywhere as a tag', () => {
    expect(parseTemplate('x<!--A-->y').body).toMatchObject([
      { kind: 'text', text: 'x' },
      { kind: 'tag', name: 'A' },
      { kind: 'text', text: 'y' },
    ]);
  });

  test('reports a container opened more often than it is closed', () => {
    expect(() => parseTemplate('\n<!--A-->one<!--A-->two<!--/A-->', { source: 'T.hde' })).toThrow(
      InvalidFileError,
    );
    expect(() => parseTemplate('\n<!--A-->one<!--A-->two<!--/A-->')).toThrow(
      /<!--A--> opened on line 2 is never closed/,
    );
  });
});

describe('renderNodes', () => {
  const nodes = (source: string): readonly TemplateNode[] => parseTemplate(source).body;

  test('substitutes tags the context knows', () => {
    const context: RenderContext = {
      resolveTag: (name) => (name === 'CHARACTER_NAME' ? 'Redshift' : undefined),
      resolveContainer: () => undefined,
    };
    expect(renderNodes(nodes('<title><!--CHARACTER_NAME--></title>'), context)).toBe(
      '<title>Redshift</title>',
    );
  });

  // HERO Designer leaves PRIMARY_OMCV and PRIMARY_DMCV in its exported sheets
  // because they are not in its tag table at all.
  test('passes an unknown tag through exactly as written', () => {
    expect(renderNodes(nodes('a<!--PRIMARY_OMCV-->b'), passThroughContext)).toBe(
      'a<!--PRIMARY_OMCV-->b',
    );
  });

  test('passes an unknown container through with its body rendered', () => {
    const context: RenderContext = {
      resolveTag: () => 'X',
      resolveContainer: () => undefined,
    };
    expect(renderNodes(nodes('<!--MYSTERY--><!--A--><!--/MYSTERY-->'), context)).toBe(
      '<!--MYSTERY-->X<!--/MYSTERY-->',
    );
  });

  test('drops the body of a container the context declines to render', () => {
    const context: RenderContext = {
      resolveTag: () => undefined,
      resolveContainer: (name) => (name === 'IFNAME' ? '' : undefined),
    };
    expect(renderNodes(nodes('a<!--IFNAME-->name: <!--NAME--><!--/IFNAME-->b'), context)).toBe('ab');
  });

  test('repeats a container body once per item, as a loop does', () => {
    let row = 0;
    const context: RenderContext = {
      resolveTag: (name) => (name === 'POWER_COST' ? String(++row * 10) : undefined),
      resolveContainer: (name, render) =>
        name === 'POWERS' ? [render(), render(), render()].join('') : undefined,
    };
    expect(renderNodes(nodes('<!--POWERS-->[<!--POWER_COST-->]<!--/POWERS-->'), context)).toBe(
      '[10][20][30]',
    );
  });

  // A false conditional collapses to an empty string in place; the spaces
  // around it stay, which is why exported sheets contain class="text-start  ".
  test('preserves surrounding whitespace when a conditional is false', () => {
    const context: RenderContext = {
      resolveTag: () => undefined,
      resolveContainer: () => '',
    };
    const source = 'class="text-start <!--IS_LIST-->list<!--/IS_LIST--> <!--IS_LIST_ITEM-->i<!--/IS_LIST_ITEM-->"';
    expect(renderNodes(nodes(source), context)).toBe('class="text-start  "');
  });

  test('leaves a conditional-only line as a blank line', () => {
    const context: RenderContext = { resolveTag: () => undefined, resolveContainer: () => '' };
    expect(renderNodes(nodes('<tr>\n<!--IFNOTES-->note<!--/IFNOTES-->\n</tr>'), context)).toBe(
      '<tr>\n\n</tr>',
    );
  });
});

describe('the real Ork template', () => {
  const source = readFileSync('fixtures/Ork-16x9.hde', 'utf8');
  const parsed = parseTemplate(source, { source: 'Ork-16x9.hde' });

  test('reads its metadata', () => {
    expect(parsed.name).toBe('Ork 16x9');
    expect(parsed.fileExtensions).toEqual(['html']);
    expect(parsed.description).toContain('This export template generates HTML');
  });

  test('reads its three fraction replacements', () => {
    expect(parsed.replacements).toMatchObject([
      { kind: 'regex', pattern: '\\b1/2d(\\d)\\b', replacement: '½d$1' },
      { kind: 'regex', pattern: '\\b1/2\\b', replacement: '½' },
      { kind: 'regex', pattern: '\\b1/4\\b', replacement: '¼' },
    ]);
  });

  // Parsing must lose nothing: rendering with a context that resolves no name
  // has to give back the source, minus only the metadata that is always cut.
  test('round-trips to the source with only the metadata prefix removed', () => {
    const rendered = renderTemplate(parsed, passThroughContext);
    expect(rendered).toBe(source.slice(983));
    expect(rendered).toStartWith('<!--\n\nGenerated by Ork HERO Templates');
  });

  // The metadata is spliced out of the middle of line 1, not deleted by line:
  // the banner comment that follows it on that same line becomes line 1 of the
  // exported sheet.
  test('leaves the banner comment as the first line, as the exported sheet has it', () => {
    const rendered = renderTemplate(parsed, passThroughContext);
    const exported = readFileSync('fixtures/Redshift.HTML', 'utf8');
    expect(rendered.split('\n')[0]).toBe('<!--');
    expect(rendered.split('\n')[0]).toBe(exported.split('\n')[0]);
  });
});
